version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server --notify-keyspace-events AKE
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379 